# the docker compose file version (not docker compose or docker version...)
version: '3.8'

# Services
services:

    # services' names can be anything :D
    # mariadb
    inception_mariadb:
        build:
            context: ./requirements/mariadb

    # nginx
    inception_nginx:
        build:
            context: ./requirements/nginx
        ports:
            - 443:443

networks:
    inception:
        driver: bridge
