version: "3.5"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dnet
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/site
    networks:
      - dnet
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/site
    networks:
      - dnet
    restart: always

networks:
  dnet:
    driver: bridge

volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      o: bind
      device: /home/jahuang/data/wordpress
  db_data:
    driver: local
    name: db_data
    driver_opts:
      type: none
      o: bind
      device: /home/jahuang/data/mariadb
