ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpass';
CREATE DATABASE IF NOT EXISTS wp_data;
CREATE USER IF NOT EXISTS 'jahuang'@'%' IDENTIFIED BY 'jahuangpass';
GRANT ALL PRIVILEGES ON *.* TO 'jahuang'@'%';
FLUSH PRIVILEGES;
